version: "2"

services:
    linuxhost:
        image: opencv:4.1.0
        stdin_open: true
        tty: true
        privileged: true
        devices:
          - "/dev/video0:/dev/video0:mwr"
          - "/dev/video1:/dev/video1:mwr"
          - "/dev/video2:/dev/video2:mwr"
        volumes:
          - /tmp/.X11-unix/:/tmp/.X11-unix
          - /home/ringo/docker/mnt:/root/mnt/
          - /home/ringo/prog/:/root/prog/
        network_mode: "host"
        environment:
          - DISPLAY=${DISPLAY}

    sshconnect:
        image: opencv:4.1.0
        stdin_open: true
        tty: true
        privileged: true
        devices:
          - "/dev/video0:/dev/video0:mwr"
          - "/dev/video1:/dev/video1:mwr"
          - "/dev/video2:/dev/video2:mwr"
        volumes:
          - /home/ringo/docker/mnt:/root/mnt/
          - $HOME/.Xauthority:/root/.Xauthority
        network_mode: "host"
        environment:
          - DISPLAY=${DISPLAY}

